package com.vasu.steelsungapi.games.domain.util;

public enum CoinFlipGameErrorEventResponse {
    COIN_FLIP_GAME_INVALID_BET_AMOUNT,
    COIN_FLIP_GAME_LOW_BALANCE,
    COIN_FLIP_GAME_INVALID_COIN_SIDE,
    COIN_FLIP_GAME_SAME_PLAYER,
    COIN_FLIP_GAME_ALREADY_JOINED,
    COIN_FLIP_GAME_ALREADY_FINISHED,
    COIN_FLIP_GAME_INVALID_MATCH_ID
}
