name: Steelsung-api workflow
on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/steelsung-api.yml'
      - 'pom.xml'

jobs:
  project-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up the Maven dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Maven dependencies & generate jar
        run: mvn clean package

      - name: Rename artifact
        run: cp target/steelsung-api-0.0.1-SNAPSHOT.jar steelsung-api-1.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: steelsung-api-artifact
          path: steelsung-api-1.jar

  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs:
      - project-build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: steelsung-api-artifact

      - name: Push to Dev server with SSH
        env:
         SSHPASS: ${{ secrets.SSHPASS }}
         SERVER: ${{ secrets.SERVER}}
        run: |
          sudo sshpass  -p ${SSHPASS}   -v  ssh -o StrictHostKeyChecking=no root@${SERVER} 'systemctl stop steelsung.api.service'
          sudo sshpass -p ${SSHPASS} scp -v  -o stricthostkeychecking=no steelsung-api-1.jar root@${SERVER}:/home/neon/steelsung-api/steelsung-api-1.jar
          sudo sshpass  -p ${SSHPASS}   -v  ssh -o StrictHostKeyChecking=no root@${SERVER} 'systemctl start steelsung.api.service'
